### PR TITLE
timestep "sixth" instead of first isn't it?

### PR DESCRIPTION
**Pull request by yvanlebras**
Dear Luise,

Looking at the new README, it seems to me there is still an error, maybe in the command line as you mention the sixth timestep, and the picture seems to me the sixth one effectively ! For information, here is the resulting visualization using Galaxy-E panoply tool:

image

### CODE REVIEW

**Comment by yvanlebras** [comment]
On my side, it has 12 timestep if I am not wrong, as seen in our related Galaxy-E history https://ecology.usegalaxy.eu/datasets/4838ba20a6d86765b2c866ff05b577b5/preview

**Comment by LuiseQuoss** [comment]
The original from the EBV Portal has 12 timesteps. But I used a subset for the README which only has 3 timesteps.

**Comment by yvanlebras** [comment]
ah ok.. but in your README R code, there is no commend line specifying you take a subset ? Or maybe I am missing it, sorry if this is the case...

**Comment by LuiseQuoss** [comment]
No you are not missing this. I never specified this in the readme. The subset was built before. I already planned about creating a different dataset for the readme. I will simply do this right now and and specify this process in the readme, so it is not confusing as it is right now.

**Pull request closed without merging**
